"""Add cash balance functionality

Revision ID: c506f7404d30
Revises: fe3dc433334c
Create Date: 2025-02-12 09:34:23.762780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c506f7404d30'
down_revision = 'fe3dc433334c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.alter_column('current_price',
               existing_type=mysql.FLOAT(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=False)
        batch_op.alter_column('price_24h_ago',
               existing_type=mysql.FLOAT(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=True)
        batch_op.alter_column('price_change_24h',
               existing_type=mysql.FLOAT(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=True)
        batch_op.alter_column('price_change_percentage_24h',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('investment_amount',
               existing_type=mysql.FLOAT(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
        batch_op.alter_column('price_at_time',
               existing_type=mysql.FLOAT(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=False)
        batch_op.alter_column('units',
               existing_type=mysql.FLOAT(precision=30, scale=10),
               type_=sa.Numeric(precision=30, scale=10),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_balance', sa.Numeric(precision=20, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cash_balance')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('units',
               existing_type=sa.Numeric(precision=30, scale=10),
               type_=mysql.FLOAT(precision=30, scale=10),
               existing_nullable=False)
        batch_op.alter_column('price_at_time',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=mysql.FLOAT(precision=20, scale=10),
               existing_nullable=False)
        batch_op.alter_column('investment_amount',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=mysql.FLOAT(precision=20, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.alter_column('price_change_percentage_24h',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('price_change_24h',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=mysql.FLOAT(precision=20, scale=10),
               existing_nullable=True)
        batch_op.alter_column('price_24h_ago',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=mysql.FLOAT(precision=20, scale=10),
               existing_nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=mysql.FLOAT(precision=20, scale=10),
               existing_nullable=False)

    op.drop_table('cash_transactions')
    # ### end Alembic commands ###
