"""add_stock_functionality

Revision ID: c5d5fba44d1e
Revises: c506f7404d30
Create Date: 2025-02-18 17:41:06.710177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d5fba44d1e'
down_revision = 'c506f7404d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('price_24h_ago', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('price_change_24h', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('price_change_percentage_24h', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('stock_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('investment_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('price_at_time', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('units', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('transaction_type', sa.String(length=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('manual_price', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transactions')
    op.drop_table('stocks')
    # ### end Alembic commands ###
