"""Add price change tracking columns to Cryptocurrency model

Revision ID: fe3dc433334c
Revises: 
Create Date: 2025-02-05 09:59:36.636859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3dc433334c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_24h_ago', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_change_24h', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_change_percentage_24h', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.drop_column('price_change_percentage_24h')
        batch_op.drop_column('price_change_24h')
        batch_op.drop_column('price_24h_ago')

    # ### end Alembic commands ###
